---
- name: Prepare the shared container image build tools
  hosts: builder
  vars:
    s2i_ci_output_dir: "{{ ansible_user_dir }}/zuul-output"
    s2i_ci_log_dir: "{{ s2i_ci_output_dir }}/logs/container-build"

  tasks:
    - name: Run host preparation tasks
      ansible.builtin.include_tasks: prepare-host-tasks.yaml
