#!/usr/bin/env bash
# Generate Zuul required-projects from sources.txt pins.
#
# Intended for the OpenDev config tenant (not the GitHub tenant for this
# repo — most OpenDev projects are not registered there). Pass
# --allow-from so the output only lists projects already in the tenant;
# anything else is still cloned by build.sh. Example:
#
#   STREAM=master ./scripts/create-zuul-required-projects.sh \
#       --output ../config/zuul.d/s2i-source-required-projects.yaml \
#       --allow-from ../config/zuul.d
#
# Regenerate after sources.txt changes.

set -euo pipefail

REPO_ROOT="${S2I_REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
STREAM="${STREAM:-master}"
OUTPUT=""
ALLOW_FROM=()

usage() {
  cat <<'EOF'
Usage: create-zuul-required-projects.sh --output PATH [--stream NAME]
       [--allow-from PATH]...

Generate the OpenDev config-tenant job fragment listing required-projects
from sources.txt. --output is required.

Options:
  --output PATH      Write the generated Zuul YAML here
  --stream NAME      sources.txt stream to scan (default: master, or $STREAM)
  --allow-from PATH  YAML file or directory of tenant project stanzas.
                     Repeatable. When set, OpenDev sources not registered
                     in those files are omitted (build.sh clones them).
  -h, --help         Show this help
EOF
}

# Extract canonical github.com / opendev.org names from `- project:` stanzas.
# Job required-projects and regex names (containing '^') are ignored.
extract_allowed_names() {
  local path="$1"
  local file
  if [[ -d "${path}" ]]; then
    find "${path}" -name '*.yaml' -print | sort | while IFS= read -r file; do
      extract_allowed_names "${file}"
    done
    return 0
  fi

  awk '
    /^- project:/ { grab=1; next }
    grab && /name:/ {
      n=$0
      sub(/^[[:space:]]*name:[[:space:]]*/, "", n)
      gsub(/["'\'']/, "", n)
      if (n ~ /^(opendev\.org|github\.com)\// && n !~ /\^/) print n
      grab=0
      next
    }
    grab && NF { grab=0 }
  ' "${path}" || true
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      if [[ $# -lt 2 || -z "${2}" ]]; then
        echo "ERROR: --output requires a path" >&2
        exit 1
      fi
      OUTPUT="$2"
      shift 2
      ;;
    --stream)
      if [[ $# -lt 2 || -z "${2}" ]]; then
        echo "ERROR: --stream requires a name" >&2
        exit 1
      fi
      STREAM="$2"
      shift 2
      ;;
    --allow-from)
      if [[ $# -lt 2 || -z "${2}" ]]; then
        echo "ERROR: --allow-from requires a path" >&2
        exit 1
      fi
      ALLOW_FROM+=("$2")
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "${OUTPUT}" ]]; then
  echo "ERROR: --output is required" >&2
  usage >&2
  exit 1
fi

if ! PROJECTS="$(
  STREAM="${STREAM}" PARALLEL="${PARALLEL:-1}" \
    bash "${REPO_ROOT}/build.sh" list-required-projects "${STREAM}"
)"; then
  echo "ERROR: list-required-projects failed" >&2
  exit 1
fi

if [[ -z "${PROJECTS}" ]]; then
  echo "ERROR: no required projects found" >&2
  exit 1
fi

ALLOWED_FILE=""
if [[ ${#ALLOW_FROM[@]} -gt 0 ]]; then
  ALLOWED_FILE="$(mktemp)"
  trap 'rm -f "${ALLOWED_FILE}"' EXIT
  for path in "${ALLOW_FROM[@]}"; do
    if [[ ! -e "${path}" ]]; then
      echo "ERROR: --allow-from path not found: ${path}" >&2
      exit 1
    fi
    extract_allowed_names "${path}"
  done | sort -u > "${ALLOWED_FILE}"

  FILTERED=""
  SKIPPED=0
  while IFS= read -r proj; do
    [[ -z "${proj}" ]] && continue
    if grep -F -x -q -- "${proj}" "${ALLOWED_FILE}"; then
      FILTERED+="${proj}"$'\n'
    else
      SKIPPED=$((SKIPPED + 1))
    fi
  done <<< "${PROJECTS}"
  PROJECTS="${FILTERED}"
  if [[ ${SKIPPED} -gt 0 ]]; then
    echo "Skipped ${SKIPPED} sources.txt projects not in --allow-from (build.sh will clone them)" >&2
  fi
fi

if [[ -z "${PROJECTS}" ]]; then
  echo "ERROR: no required projects remain after --allow-from filter" >&2
  exit 1
fi

PROJECT_COUNT="$(printf '%s\n' "${PROJECTS}" | grep -c .)"

mkdir -p "$(dirname "${OUTPUT}")"

{
  cat <<'EOF'
# Generated by scripts/create-zuul-required-projects.sh in
# openstack-k8s-operators/s2i-openstack-containers — do not edit.
# Regenerate with:
#   cd s2i-openstack-containers && STREAM=master \
#     ./scripts/create-zuul-required-projects.sh \
#     --output ../config/zuul.d/s2i-source-required-projects.yaml \
#     --allow-from ../config/zuul.d
---
- job:
    name: s2i-openstack-zuul-sources-base
    abstract: true
    parent: base
    description: |
      Abstract base listing upstream repos referenced by sources.txt.
      Child jobs inherit these required-projects so Zuul clones
      OpenDev sources instead of build.sh cloning them over the network.
      Only tenant-registered projects are listed; others are cloned by
      build.sh when they are absent from the Zuul workspace.
    required-projects:
      - github.com/openstack-k8s-operators/s2i-openstack-containers
      - opendev.org/zuul/zuul-jobs
EOF
  while IFS= read -r proj; do
    [[ -z "${proj}" ]] && continue
    printf '      - %s\n' "${proj}"
  done <<< "${PROJECTS}"
} > "${OUTPUT}"

echo "Wrote ${PROJECT_COUNT} projects to ${OUTPUT}"
