/*
Copyright 2026 Red Hat

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// gen-users writes users.Registry to a plain text file readable by bash's
// read/awk without any YAML or Python parser.
//
// Usage: go run ./cmd/gen-users <output-file>
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/openstack-k8s-operators/s2i-openstack-containers/users"
)

func main() {
	names := make([]string, 0, len(users.Registry))
	for name := range users.Registry {
		names = append(names, name)
	}
	sort.Strings(names)

	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "Usage: gen-users <output-file>")
		os.Exit(1)
	}
	out, err := os.Create(os.Args[1])
	if err != nil {
		fmt.Fprintf(os.Stderr, "error creating output file: %v\n", err)
		os.Exit(1)
	}

	w := func(format string, args ...any) {
		if err != nil {
			return
		}
		_, err = fmt.Fprintf(out, format, args...)
	}

	w("# Code generated by gen-users from users.Registry. DO NOT EDIT.\n")
	w("# Source of truth: users/registry.go\n")
	w("# Regenerate with: make generate-service-uids\n")
	w("#\n")
	w("# Format: name uid gid home groups\n")
	w("# home is - if unset, groups is - if unset\n")

	for _, name := range names {
		svc := users.Registry[name]
		home := "-"
		if svc.Home != "" {
			home = svc.Home
		}
		groups := "-"
		if len(svc.Groups) > 0 {
			groups = strings.Join(svc.Groups, ",")
		}
		w("%s %d %d %s %s\n", name, svc.UID, svc.GID, home, groups)
	}

	if closeErr := out.Close(); closeErr != nil && err == nil {
		err = closeErr
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "error writing output file: %v\n", err)
		os.Exit(1)
	}
}
