name: Build images

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: quay.io
      NAMESPACE: openstack-k8s-operators
      TAG: "master-latest,master-${{ github.sha }}"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/setup-tox

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y buildah podman

      - name: Build images
        run: tox -e build

      - name: list images
        run: podman images
